# Generated by Django 5.2 on 2025-05-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_marketplacelink_productcolor_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Фото')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='content.productcolor')),
            ],
        ),
    ]
