# Generated by Django 5.2 on 2025-05-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_productcolorimage_productcolorsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subsubcat',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.shopcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.shopsubcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.shopsubsubcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color_image',
            field=models.ImageField(default=1, upload_to='color_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='marketplace_amazon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='marketplace_wb',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(upload_to='product_color_images/'),
        ),
        migrations.AlterField(
            model_name='productcolorsize',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='MarketplaceLink',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
