# Generated by Django 5.2 on 2025-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_amazon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_wb',
            field=models.URLField(blank=True),
        ),
    ]
