# Generated by Django 5.2 on 2025-05-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_product_composition_productimage_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketplace_amazon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketplace_wb',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subsubcategory',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='marketplace_amazon',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='marketplace_wb',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='images',
            field=models.ManyToManyField(blank=True, to='content.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='content.productcolor'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='content.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='marketplace_links',
            field=models.ManyToManyField(to='content.marketplacelink'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='content.size'),
        ),
    ]
