# Generated by Django 5.2 on 2025-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_marketplacelink_size_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='images',
        ),
    ]
