# Generated by Django 5.2 on 2025-05-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_productcolor_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccordionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accordion_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_blocks', to='content.product')),
            ],
        ),
    ]
