# Generated by Django 5.2 on 2025-05-04 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='content.shopcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='content.shopsubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop_subsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='content.shopsubsubcategory'),
        ),
    ]
