# Generated by Django 5.2 on 2025-05-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_product_shop_category_product_shop_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size_objects', to='content.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='system',
            field=models.CharField(choices=[('EU', 'EU'), ('UK', 'UK'), ('US', 'US')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='value',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
