# Generated by Django 5.2 on 2025-05-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_product_sizes_remove_size_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
