# Generated by Django 5.2 on 2025-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_product_sizes_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='men', max_length=10),
        ),
    ]
