# Generated by Django 5.2 on 2025-05-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_shopcategory_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSubSubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/subsubsubcategories/')),
                ('link', models.URLField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubsubcategories', to='content.shopsubsubcategory')),
            ],
            options={
                'verbose_name': 'Shop Sub Sub Sub Category',
                'verbose_name_plural': 'Shop Sub Sub Sub Categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
