# Generated by Django 5.2 on 2025-05-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_shopsubsubsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_subsubsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='content.shopsubsubsubcategory'),
        ),
    ]
