# Generated by Django 5.2 on 2025-05-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_remove_shopsubsubcategory_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.productcolor'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='image',
            field=models.ImageField(upload_to='color_images/'),
        ),
    ]
