# Generated by Django 5.2 on 2025-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_productcolorimage_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketplace_links',
            field=models.ManyToManyField(blank=True, to='content.marketplacelink'),
        ),
    ]
